package com.linkopus.ms.utils.ressources.enums;

public enum ErrorTypes {
	ROLE_HEADER_IS_REQUIRED, EMAIL_HEADER_IS_REQUIRED, TEAM_HEADER_IS_REQUIRED, INVALID_EMAIL_FORMAT, NOT_REQUIRED_ROLE, ROUTE_NOT_FOUND, UNEXPECTED_ERROR, INVALID_ROLE, USER_NOT_FOUND, LOG_FILE_NOT_FOUND
}
